/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TP6vistas;

import TP6.Directorio;

/**
 *
 * @author Chony
 */
public class ViewMenu extends javax.swing.JFrame {
private Directorio directorio=new Directorio();
    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jComboBox2 = new javax.swing.JComboBox<>();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAgregarCliente = new javax.swing.JMenu();
        jmiAgregar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiBuscarporTelefono = new javax.swing.JMenuItem();
        jmiBuscarporApellido = new javax.swing.JMenuItem();
        jmiBuscarporCiudad = new javax.swing.JMenuItem();
        jmBorrarCliente = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buen Dia");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jmAgregarCliente.setText("AgregarCliente");
        jmAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarClienteActionPerformed(evt);
            }
        });

        jmiAgregar.setText("Agregar");
        jmiAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarActionPerformed(evt);
            }
        });
        jmAgregarCliente.add(jmiAgregar);

        jMenuBar1.add(jmAgregarCliente);

        jMenu6.setText("BuscarCliente");

        jmiBuscarporTelefono.setText("por teléfono");
        jmiBuscarporTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarporTelefonoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiBuscarporTelefono);

        jmiBuscarporApellido.setText("por apellido");
        jmiBuscarporApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarporApellidoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiBuscarporApellido);

        jmiBuscarporCiudad.setText("por ciudad");
        jmiBuscarporCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarporCiudadActionPerformed(evt);
            }
        });
        jMenu6.add(jmiBuscarporCiudad);

        jMenuBar1.add(jMenu6);

        jmBorrarCliente.setText("BorrarCliente");

        jMenuItem2.setText("Borrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmBorrarCliente.add(jMenuItem2);

        jMenuBar1.add(jmBorrarCliente);

        jmSalir.setText("Salida");

        salida.setText("Salir");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        jmSalir.add(salida);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarClienteActionPerformed
       
        
    }//GEN-LAST:event_jmAgregarClienteActionPerformed

    private void jmiAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        ViewAgregarCliente a=new ViewAgregarCliente(directorio);
        a.setVisible(true);
        escritorio.add(a);
        escritorio.moveToFront(a);
    }//GEN-LAST:event_jmiAgregarActionPerformed

    private void jmiBuscarporTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarporTelefonoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        ViewBuscarClienteTelefono b=new ViewBuscarClienteTelefono();
        b.setVisible(true);
        escritorio.add(b);
        escritorio.moveToFront(b);
    }//GEN-LAST:event_jmiBuscarporTelefonoActionPerformed

    private void jmiBuscarporApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarporApellidoActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        
        ViewBuscarClienteApellido c=new ViewBuscarClienteApellido();
        c.setVisible(true);
        escritorio.add(c);
        escritorio.moveToFront(c);
    }//GEN-LAST:event_jmiBuscarporApellidoActionPerformed

    private void jmiBuscarporCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarporCiudadActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        
        ViewBuscarClienteCiudad d=new ViewBuscarClienteCiudad();
        d.setVisible(true);
        escritorio.add(d);
        escritorio.moveToFront(d);
    }//GEN-LAST:event_jmiBuscarporCiudadActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        
        ViewBorrarCliente borrar=new ViewBorrarCliente();
        borrar.setVisible(true);
        escritorio.add(borrar);
        escritorio.moveToFront(borrar);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        dispose();
    }//GEN-LAST:event_salidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jmAgregarCliente;
    private javax.swing.JMenu jmBorrarCliente;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAgregar;
    private javax.swing.JMenuItem jmiBuscarporApellido;
    private javax.swing.JMenuItem jmiBuscarporCiudad;
    private javax.swing.JMenuItem jmiBuscarporTelefono;
    private javax.swing.JMenuItem salida;
    // End of variables declaration//GEN-END:variables
}
